"""여행 요청/계획 스키마에서 사용하는 Enum 정의."""

from enum import StrEnum


class Region(StrEnum):
    """여행 지역 Enum."""

    SEOUL = "SEOUL"
    BUSAN = "BUSAN"
    JEJU_CITY = "JEJU_CITY"
    GYEONGJU = "GYEONGJU"
    TOKYO = "TOKYO"
    OSAKA = "OSAKA"
    KYOTO = "KYOTO"
    HOKKAIDO = "HOKKAIDO"
    OKINAWA_PREFECTURE = "OKINAWA_PREFECTURE"
    BEIJING = "BEIJING"
    SHANGHAI = "SHANGHAI"
    TAIPEI = "TAIPEI"
    HONG_KONG = "HONG_KONG"
    SINGAPORE = "SINGAPORE"
    KUALA_LUMPUR = "KUALA_LUMPUR"
    BANGKOK = "BANGKOK"
    PHUKET_PROVINCE = "PHUKET_PROVINCE"
    CHIANG_MAI = "CHIANG_MAI"
    HANOI = "HANOI"
    HO_CHI_MINH_CITY = "HO_CHI_MINH_CITY"
    DA_NANG = "DA_NANG"
    MANILA = "MANILA"
    CEBU_CITY = "CEBU_CITY"
    BALI = "BALI"
    JAKARTA = "JAKARTA"
    NEW_DELHI = "NEW_DELHI"
    MUMBAI = "MUMBAI"
    MALDIVES = "MALDIVES"
    COLOMBO = "COLOMBO"
    KATHMANDU = "KATHMANDU"
    NEW_YORK_CITY = "NEW_YORK_CITY"
    LOS_ANGELES = "LOS_ANGELES"
    SAN_FRANCISCO = "SAN_FRANCISCO"
    LAS_VEGAS = "LAS_VEGAS"
    CHICAGO = "CHICAGO"
    MIAMI = "MIAMI"
    HAWAII = "HAWAII"
    VANCOUVER = "VANCOUVER"
    TORONTO = "TORONTO"
    MONTREAL = "MONTREAL"
    CANCUN = "CANCUN"
    MEXICO_CITY = "MEXICO_CITY"
    HAVANA = "HAVANA"
    RIO_DE_JANEIRO = "RIO_DE_JANEIRO"
    SAO_PAULO = "SAO_PAULO"
    BUENOS_AIRES = "BUENOS_AIRES"
    SANTIAGO = "SANTIAGO"
    CUSCO = "CUSCO"
    LIMA = "LIMA"
    CARTAGENA = "CARTAGENA"
    PARIS = "PARIS"
    NICE = "NICE"
    LONDON = "LONDON"
    EDINBURGH = "EDINBURGH"
    BERLIN = "BERLIN"
    MUNICH = "MUNICH"
    ROME = "ROME"
    VENICE = "VENICE"
    MILAN = "MILAN"
    FLORENCE = "FLORENCE"
    BARCELONA = "BARCELONA"
    MADRID = "MADRID"
    SEVILLE = "SEVILLE"
    LISBON = "LISBON"
    PORTO = "PORTO"
    AMSTERDAM = "AMSTERDAM"
    BRUSSELS = "BRUSSELS"
    ZURICH = "ZURICH"
    INTERLAKEN = "INTERLAKEN"
    VIENNA = "VIENNA"
    SALZBURG = "SALZBURG"
    PRAGUE = "PRAGUE"
    WARSAW = "WARSAW"
    KRAKOW = "KRAKOW"
    BUDAPEST = "BUDAPEST"
    ATHENS = "ATHENS"
    SANTORINI = "SANTORINI"
    DUBROVNIK = "DUBROVNIK"
    REYKJAVIK = "REYKJAVIK"
    OSLO = "OSLO"
    BERGEN = "BERGEN"
    STOCKHOLM = "STOCKHOLM"
    COPENHAGEN = "COPENHAGEN"
    HELSINKI = "HELSINKI"
    MOSCOW = "MOSCOW"
    SAINT_PETERSBURG = "SAINT_PETERSBURG"
    ISTANBUL = "ISTANBUL"
    CAPPADOCIA = "CAPPADOCIA"
    DUBAI = "DUBAI"
    ABU_DHABI = "ABU_DHABI"
    TEL_AVIV = "TEL_AVIV"
    JERUSALEM = "JERUSALEM"
    PETRA = "PETRA"
    CAIRO = "CAIRO"
    MARRAKESH = "MARRAKESH"
    CASABLANCA = "CASABLANCA"
    CAPE_TOWN = "CAPE_TOWN"
    JOHANNESBURG = "JOHANNESBURG"
    NAIROBI = "NAIROBI"
    ZANZIBAR = "ZANZIBAR"
    SYDNEY = "SYDNEY"
    MELBOURNE = "MELBOURNE"
    GOLD_COAST = "GOLD_COAST"
    CAIRNS = "CAIRNS"
    AUCKLAND = "AUCKLAND"
    QUEENSTOWN = "QUEENSTOWN"
    SUVA = "SUVA"


class CompanionType(StrEnum):
    """동행자 유형 Enum."""

    FAMILY = "FAMILY"
    FRIENDS = "FRIENDS"
    COUPLE = "COUPLE"
    SPOUSE = "SPOUSE"
    CHILDREN = "CHILDREN"
    PARENTS = "PARENTS"
    TEACHER = "TEACHER"
    STUDENTS = "STUDENTS"
    COLLEAGUES = "COLLEAGUES"
    SENIORS = "SENIORS"
    SOLO = "SOLO"


class TravelTheme(StrEnum):
    """여행 테마 Enum."""

    UNIQUE_TRIP = "UNIQUE_TRIP"
    HONEYMOON = "HONEYMOON"
    FAMILY_TRIP = "FAMILY_TRIP"
    HEALING = "HEALING"
    SIGHTSEEING = "SIGHTSEEING"
    FOOD_TOUR = "FOOD_TOUR"
    NATURE = "NATURE"
    SHOPPING = "SHOPPING"
    CULTURE_ART = "CULTURE_ART"
    ACTIVITY = "ACTIVITY"
    CITY_TRIP = "CITY_TRIP"
    PHOTO_SPOTS = "PHOTO_SPOTS"


class PacePreference(StrEnum):
    """여행 일정 밀도 선호 Enum."""

    DENSE = "DENSE"
    RELAXED = "RELAXED"


class PlanningPreference(StrEnum):
    """여행 계획 성향 Enum."""

    PLANNED = "PLANNED"
    SPONTANEOUS = "SPONTANEOUS"


class DestinationPreference(StrEnum):
    """여행지 선호 Enum."""

    TOURIST_SPOTS = "TOURIST_SPOTS"
    LOCAL_EXPERIENCE = "LOCAL_EXPERIENCE"


class ActivityPreference(StrEnum):
    """활동 선호 Enum."""

    ACTIVE = "ACTIVE"
    REST_FOCUSED = "REST_FOCUSED"


class PriorityPreference(StrEnum):
    """우선 가치 선호 Enum."""

    EFFICIENCY = "EFFICIENCY"
    EMOTIONAL = "EMOTIONAL"


class BudgetRange(StrEnum):
    """예산 범위 Enum."""

    LOW = "LOW"
    MID = "MID"
    HIGH = "HIGH"
    LUXURY = "LUXURY"


class ChatOperation(StrEnum):
    """로드맵 대화의 수정 Operation 타입 Enum."""

    REPLACE = "REPLACE"
    ADD = "ADD"
    REMOVE = "REMOVE"
    MOVE = "MOVE"


class ChatStatus(StrEnum):
    """로드맵 대화 결과 상태 Enum."""

    GENERAL_CHAT = "GENERAL_CHAT"
    SUCCESS = "SUCCESS"
    ASK_CLARIFICATION = "ASK_CLARIFICATION"
    REJECTED = "REJECTED"
