# ruff: noqa: E501
"""도시 이름 매핑과 크롤링 대상 도시 목록."""

NAME_MAPPING = {
    "서울": "Seoul",
    "부산": "Busan",
    "제주": {"wikipedia": "Jeju City", "wikitravel": "Jeju"},
    "경주": "Gyeongju",
    "도쿄": "Tokyo",
    "오사카": "Osaka",
    "교토": "Kyoto",
    "홋카이도": "Hokkaido",
    "오키나와": {"wikipedia": "Okinawa Prefecture", "wikitravel": "Okinawa"},
    "베이징": "Beijing",
    "상하이": "Shanghai",
    "타이베이": "Taipei",
    "홍콩": "Hong Kong",
    "싱가포르": "Singapore",
    "쿠알라룸푸르": "Kuala Lumpur",
    "방콕": "Bangkok",
    "푸켓": {"wikipedia": "Phuket Province", "wikitravel": "Phuket"},
    "치앙마이": "Chiang Mai",
    "하노이": "Hanoi",
    "호치민": "Ho Chi Minh City",
    "다낭": "Da Nang",
    "마닐라": "Manila",
    "세부": "Cebu City",
    "발리": "Bali",
    "자카르타": "Jakarta",
    "뉴델리": "New Delhi",
    "뭄바이": "Mumbai",
    "몰디브": "Maldives",
    "콜롬보": "Colombo",
    "카트만두": "Kathmandu",
    "뉴욕": "New York City",
    "로스앤젤레스": "Los Angeles",
    "샌프란시스코": "San Francisco",
    "라스베이거스": "Las Vegas",
    "시카고": "Chicago",
    "마이애미": "Miami",
    "하와이": "Hawaii",
    "밴쿠버": "Vancouver",
    "토론토": "Toronto",
    "몬트리올": "Montreal",
    "칸쿤": "Cancún",
    "멕시코시티": "Mexico City",
    "하바나": "Havana",
    "리우데자네이루": "Rio de Janeiro",
    "상파울루": "São Paulo",
    "부에노스아이레스": "Buenos Aires",
    "산티아고": "Santiago",
    "쿠스코": "Cusco",
    "리마": "Lima",
    "카르타헤나": "Cartagena",
    "파리": "Paris",
    "니스": "Nice",
    "런던": "London",
    "에든버러": "Edinburgh",
    "베를린": "Berlin",
    "뮌헨": "Munich",
    "로마": "Rome",
    "베네치아": "Venice",
    "밀라노": "Milan",
    "피렌체": "Florence",
    "바르셀로나": "Barcelona",
    "마드리드": "Madrid",
    "세비야": "Seville",
    "리스본": "Lisbon",
    "포르투": "Porto",
    "암스테르담": "Amsterdam",
    "브뤼셀": "Brussels",
    "취리히": "Zürich",
    "인터라켄": "Interlaken",
    "비엔나": "Vienna",
    "잘츠부르크": "Salzburg",
    "프라하": "Prague",
    "바르샤바": "Warsaw",
    "크라쿠프": "Kraków",
    "부다페스트": "Budapest",
    "아테네": "Athens",
    "산토리니": "Santorini",
    "두브로브니크": "Dubrovnik",
    "레이캬비크": "Reykjavik",
    "오슬로": "Oslo",
    "베르겐": "Bergen",
    "스톡홀름": "Stockholm",
    "코펜하겐": "Copenhagen",
    "헬싱키": "Helsinki",
    "모스크바": "Moscow",
    "상트페테르부르크": "Saint Petersburg",
    "이스탄불": "Istanbul",
    "카파도키아": "Cappadocia",
    "두바이": "Dubai",
    "아부다비": "Abu Dhabi",
    "텔아비브": "Tel Aviv",
    "예루살렘": "Jerusalem",
    "페트라": "Petra",
    "카이로": "Cairo",
    "마라케시": "Marrakesh",
    "카사블랑카": "Casablanca",
    "케이프타운": "Cape Town",
    "요하네스버그": "Johannesburg",
    "나이로비": "Nairobi",
    "잔지바르": "Zanzibar",
    "시드니": "Sydney",
    "멜버른": "Melbourne",
    "골드코스트": "Gold Coast",
    "케언즈": "Cairns",
    "오클랜드": "Auckland",
    "퀸스타운": "Queenstown",
    "수바": "Suva",
}
