"""Google Places type을 Mohaeng 도메인 장소 카테고리로 매핑합니다."""

from __future__ import annotations

from enum import StrEnum


class PlaceCategory(StrEnum):
    """최종 응답에 노출하는 Mohaeng 장소 대분류 코드."""

    FOOD = "FOOD"
    CAFE = "CAFE"
    ATTRACTION = "ATTRACTION"
    CULTURE = "CULTURE"
    NATURE = "NATURE"
    SHOPPING = "SHOPPING"
    LODGING = "LODGING"
    TRANSPORT = "TRANSPORT"
    ENTERTAINMENT = "ENTERTAINMENT"
    WELLNESS = "WELLNESS"
    SERVICE = "SERVICE"
    OTHER = "OTHER"


_GENERIC_TYPES = {
    "establishment",
    "finance",
    "food",
    "geocode",
    "health",
    "intersection",
    "plus_code",
    "point_of_interest",
    "political",
    "premise",
    "route",
    "street_address",
    "subpremise",
}

_CAFE_TYPES = {
    "bagel_shop",
    "bakery",
    "cafe",
    "cafeteria",
    "cake_shop",
    "candy_store",
    "cat_cafe",
    "chocolate_factory",
    "chocolate_shop",
    "coffee_roastery",
    "coffee_shop",
    "coffee_stand",
    "confectionery",
    "dessert_restaurant",
    "dessert_shop",
    "dog_cafe",
    "donut_shop",
    "ice_cream_shop",
    "internet_cafe",
    "juice_shop",
    "pastry_shop",
    "tea_house",
    "tea_store",
}

_FOOD_TYPES = {
    "acai_shop",
    "afghani_restaurant",
    "african_restaurant",
    "american_restaurant",
    "argentinian_restaurant",
    "asian_fusion_restaurant",
    "asian_restaurant",
    "australian_restaurant",
    "austrian_restaurant",
    "bar",
    "bar_and_grill",
    "barbecue_area",
    "barbecue_restaurant",
    "basque_restaurant",
    "bavarian_restaurant",
    "beer_garden",
    "belgian_restaurant",
    "bistro",
    "brazilian_restaurant",
    "breakfast_restaurant",
    "brewery",
    "brewpub",
    "british_restaurant",
    "brunch_restaurant",
    "buffet_restaurant",
    "burmese_restaurant",
    "burrito_restaurant",
    "cajun_restaurant",
    "californian_restaurant",
    "cambodian_restaurant",
    "cantonese_restaurant",
    "caribbean_restaurant",
    "catering_service",
    "chicken_restaurant",
    "chicken_wings_restaurant",
    "chilean_restaurant",
    "chinese_noodle_restaurant",
    "chinese_restaurant",
    "cocktail_bar",
    "colombian_restaurant",
    "croatian_restaurant",
    "cuban_restaurant",
    "czech_restaurant",
    "danish_restaurant",
    "deli",
    "dim_sum_restaurant",
    "diner",
    "dumpling_restaurant",
    "dutch_restaurant",
    "eastern_european_restaurant",
    "ethiopian_restaurant",
    "european_restaurant",
    "falafel_restaurant",
    "family_restaurant",
    "fast_food_restaurant",
    "filipino_restaurant",
    "fine_dining_restaurant",
    "fish_and_chips_restaurant",
    "fondue_restaurant",
    "food_court",
    "food_delivery",
    "french_restaurant",
    "fusion_restaurant",
    "gastropub",
    "german_restaurant",
    "greek_restaurant",
    "gyro_restaurant",
    "halal_restaurant",
    "hamburger_restaurant",
    "hawaiian_restaurant",
    "hookah_bar",
    "hot_dog_restaurant",
    "hot_dog_stand",
    "hot_pot_restaurant",
    "hungarian_restaurant",
    "indian_restaurant",
    "indonesian_restaurant",
    "irish_pub",
    "irish_restaurant",
    "israeli_restaurant",
    "italian_restaurant",
    "japanese_curry_restaurant",
    "japanese_izakaya_restaurant",
    "japanese_restaurant",
    "kebab_shop",
    "korean_barbecue_restaurant",
    "korean_restaurant",
    "latin_american_restaurant",
    "lebanese_restaurant",
    "lounge_bar",
    "malaysian_restaurant",
    "meal_delivery",
    "meal_takeaway",
    "mediterranean_restaurant",
    "mexican_restaurant",
    "middle_eastern_restaurant",
    "mongolian_barbecue_restaurant",
    "moroccan_restaurant",
    "noodle_shop",
    "north_indian_restaurant",
    "oyster_bar_restaurant",
    "pakistani_restaurant",
    "persian_restaurant",
    "peruvian_restaurant",
    "pizza_delivery",
    "pizza_restaurant",
    "polish_restaurant",
    "portuguese_restaurant",
    "pub",
    "ramen_restaurant",
    "restaurant",
    "romanian_restaurant",
    "russian_restaurant",
    "salad_shop",
    "sandwich_shop",
    "scandinavian_restaurant",
    "seafood_restaurant",
    "shawarma_restaurant",
    "snack_bar",
    "soul_food_restaurant",
    "soup_restaurant",
    "south_american_restaurant",
    "south_indian_restaurant",
    "southwestern_us_restaurant",
    "spanish_restaurant",
    "sports_bar",
    "sri_lankan_restaurant",
    "steak_house",
    "sushi_restaurant",
    "swiss_restaurant",
    "taco_restaurant",
    "taiwanese_restaurant",
    "tapas_restaurant",
    "tex_mex_restaurant",
    "thai_restaurant",
    "tibetan_restaurant",
    "tonkatsu_restaurant",
    "turkish_restaurant",
    "ukrainian_restaurant",
    "vegan_restaurant",
    "vegetarian_restaurant",
    "vietnamese_restaurant",
    "western_restaurant",
    "wine_bar",
    "winery",
    "yakiniku_restaurant",
    "yakitori_restaurant",
}

_CULTURE_TYPES = {
    "art_gallery",
    "art_museum",
    "art_studio",
    "auditorium",
    "castle",
    "cultural_center",
    "cultural_landmark",
    "fountain",
    "historical_landmark",
    "historical_place",
    "history_museum",
    "library",
    "monument",
    "museum",
    "opera_house",
    "performing_arts_theater",
    "philharmonic_hall",
    "planetarium",
    "sculpture",
}

_NATURE_TYPES = {
    "beach",
    "botanical_garden",
    "garden",
    "hiking_area",
    "island",
    "lake",
    "mountain_peak",
    "national_park",
    "nature_preserve",
    "park",
    "river",
    "scenic_spot",
    "state_park",
    "wildlife_park",
    "wildlife_refuge",
    "woods",
    "zoo",
}

_ATTRACTION_TYPES = {
    "landmark",
    "observation_deck",
    "plaza",
    "tourist_attraction",
    "town_square",
    "visitor_center",
}

_SHOPPING_TYPES = {
    "asian_grocery_store",
    "auto_parts_store",
    "bicycle_store",
    "book_store",
    "building_materials_store",
    "butcher_shop",
    "cell_phone_store",
    "clothing_store",
    "convenience_store",
    "cosmetics_store",
    "department_store",
    "discount_store",
    "discount_supermarket",
    "electronics_store",
    "farmers_market",
    "flea_market",
    "florist",
    "food_store",
    "furniture_store",
    "garden_center",
    "general_store",
    "gift_shop",
    "grocery_store",
    "hardware_store",
    "health_food_store",
    "home_goods_store",
    "home_improvement_store",
    "hypermarket",
    "jewelry_store",
    "liquor_store",
    "market",
    "pet_store",
    "shoe_store",
    "shopping_mall",
    "sporting_goods_store",
    "sportswear_store",
    "store",
    "supermarket",
    "thrift_store",
    "toy_store",
    "warehouse_store",
    "wholesaler",
    "womens_clothing_store",
}

_LODGING_TYPES = {
    "bed_and_breakfast",
    "budget_japanese_inn",
    "campground",
    "camping_cabin",
    "cottage",
    "extended_stay_hotel",
    "farmstay",
    "guest_house",
    "hostel",
    "hotel",
    "inn",
    "japanese_inn",
    "lodging",
    "mobile_home_park",
    "motel",
    "private_guest_room",
    "resort_hotel",
    "rv_park",
}

_TRANSPORT_TYPES = {
    "airport",
    "airstrip",
    "bike_sharing_station",
    "bridge",
    "bus_station",
    "bus_stop",
    "car_rental",
    "ebike_charging_station",
    "electric_vehicle_charging_station",
    "ferry_service",
    "ferry_terminal",
    "gas_station",
    "heliport",
    "international_airport",
    "light_rail_station",
    "park_and_ride",
    "parking",
    "parking_garage",
    "parking_lot",
    "rest_stop",
    "subway_station",
    "taxi_service",
    "taxi_stand",
    "toll_station",
    "train_station",
    "train_ticket_office",
    "tram_stop",
    "transit_depot",
    "transit_station",
    "transit_stop",
    "transportation_service",
    "truck_stop",
}

_ENTERTAINMENT_TYPES = {
    "adventure_sports_center",
    "amphitheatre",
    "amusement_center",
    "amusement_park",
    "aquarium",
    "banquet_hall",
    "bowling_alley",
    "casino",
    "childrens_camp",
    "city_park",
    "comedy_club",
    "community_center",
    "concert_hall",
    "convention_center",
    "cycling_park",
    "dance_hall",
    "dog_park",
    "event_venue",
    "ferris_wheel",
    "go_karting_venue",
    "indoor_playground",
    "karaoke",
    "live_music_venue",
    "marina",
    "miniature_golf_course",
    "movie_rental",
    "movie_theater",
    "night_club",
    "off_roading_area",
    "paintball_center",
    "picnic_ground",
    "roller_coaster",
    "skateboard_park",
    "video_arcade",
    "vineyard",
    "water_park",
    "wedding_venue",
}

_WELLNESS_TYPES = {
    "chiropractor",
    "dental_clinic",
    "dentist",
    "doctor",
    "drugstore",
    "fitness_center",
    "general_hospital",
    "gym",
    "hospital",
    "massage",
    "massage_spa",
    "medical_center",
    "medical_clinic",
    "medical_lab",
    "pharmacy",
    "physiotherapist",
    "public_bath",
    "sauna",
    "skin_care_clinic",
    "spa",
    "swimming_pool",
    "tanning_studio",
    "wellness_center",
    "yoga_studio",
}

_SERVICE_TYPES = {
    "academic_department",
    "accounting",
    "administrative_area_level_1",
    "administrative_area_level_2",
    "administrative_area_level_3",
    "administrative_area_level_4",
    "administrative_area_level_5",
    "administrative_area_level_6",
    "administrative_area_level_7",
    "aircraft_rental_service",
    "apartment_building",
    "apartment_complex",
    "archipelago",
    "arena",
    "association_or_organization",
    "astrologer",
    "athletic_field",
    "atm",
    "bank",
    "barber_shop",
    "beautician",
    "beauty_salon",
    "body_art_service",
    "buddhist_temple",
    "business_center",
    "car_dealer",
    "car_repair",
    "car_wash",
    "cemetery",
    "chauffeur_service",
    "child_care_agency",
    "church",
    "city_hall",
    "colloquial_area",
    "condominium_complex",
    "consultant",
    "continent",
    "corporate_office",
    "country",
    "courier_service",
    "courthouse",
    "coworking_space",
    "educational_institution",
    "electrician",
    "embassy",
    "employment_agency",
    "farm",
    "fire_station",
    "fishing_charter",
    "fishing_pier",
    "fishing_pond",
    "floor",
    "foot_care",
    "funeral_home",
    "general_contractor",
    "government_office",
    "golf_course",
    "hair_care",
    "hair_salon",
    "hindu_temple",
    "housing_complex",
    "ice_skating_rink",
    "indoor_golf_course",
    "insurance_agency",
    "laundry",
    "lawyer",
    "local_government_office",
    "locality",
    "locksmith",
    "makeup_artist",
    "manufacturer",
    "marketing_consultant",
    "mosque",
    "moving_company",
    "nail_salon",
    "neighborhood",
    "neighborhood_police_station",
    "non_profit_organization",
    "painter",
    "pet_boarding_service",
    "pet_care",
    "place_of_worship",
    "playground",
    "plumber",
    "police",
    "post_box",
    "post_office",
    "postal_code",
    "postal_code_prefix",
    "postal_code_suffix",
    "postal_town",
    "preschool",
    "primary_school",
    "psychic",
    "public_bathroom",
    "race_course",
    "ranch",
    "real_estate_agency",
    "research_institute",
    "roofing_contractor",
    "room",
    "school",
    "school_district",
    "secondary_school",
    "service",
    "shipping_service",
    "shinto_shrine",
    "ski_resort",
    "sports_activity_location",
    "sports_club",
    "sports_coaching",
    "sports_complex",
    "sports_school",
    "stable",
    "stadium",
    "storage",
    "street_number",
    "sublocality",
    "sublocality_level_1",
    "sublocality_level_2",
    "sublocality_level_3",
    "sublocality_level_4",
    "sublocality_level_5",
    "summer_camp_organizer",
    "supplier",
    "synagogue",
    "tailor",
    "telecommunications_service_provider",
    "television_studio",
    "tennis_court",
    "tire_shop",
    "tour_agency",
    "tourist_information_center",
    "travel_agency",
    "truck_dealer",
    "university",
    "veterinary_care",
}

_CATEGORY_BY_PRIORITY: tuple[tuple[PlaceCategory, set[str]], ...] = (
    (PlaceCategory.CAFE, _CAFE_TYPES),
    (PlaceCategory.FOOD, _FOOD_TYPES),
    (PlaceCategory.ATTRACTION, _ATTRACTION_TYPES),
    (PlaceCategory.CULTURE, _CULTURE_TYPES),
    (PlaceCategory.NATURE, _NATURE_TYPES),
    (PlaceCategory.SHOPPING, _SHOPPING_TYPES),
    (PlaceCategory.LODGING, _LODGING_TYPES),
    (PlaceCategory.TRANSPORT, _TRANSPORT_TYPES),
    (PlaceCategory.ENTERTAINMENT, _ENTERTAINMENT_TYPES),
    (PlaceCategory.WELLNESS, _WELLNESS_TYPES),
    (PlaceCategory.SERVICE, _SERVICE_TYPES),
)


def _normalize_place_type(place_type: str | None) -> str:
    return (place_type or "").strip().lower().rstrip("*")


def resolve_place_category(primary_type: str | None, types: list[str] | None = None) -> PlaceCategory:
    """Google Places primaryType/types를 서비스 도메인 카테고리로 변환합니다."""
    candidates = []
    for place_type in [primary_type, *(types or [])]:
        normalized = _normalize_place_type(place_type)
        if normalized and normalized not in candidates:
            candidates.append(normalized)

    if not candidates or all(place_type in _GENERIC_TYPES for place_type in candidates):
        return PlaceCategory.OTHER

    candidate_set = set(candidates)
    for category, mapped_types in _CATEGORY_BY_PRIORITY:
        if candidate_set & mapped_types:
            return category

    return PlaceCategory.OTHER
